---
title: "Using the `censusxy` Package"
author: "Branson Fox and Christopher Prener"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{stlcsb}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Overview

The `censusxy` package is designed to provide easy and efficient access to the [US Census Bureau Batch Geocoder](https://geocoding.geo.census.gov/geocoder/geographies/addressbatch?form) in `R`. It was developed specifically to work with large objects of the data.frame class.
 
## Workflow

The geocode function includes an optional argument `start` which allows the user to subset by thousands of rows. This serves two protections. First, if your internet connection times out or your computer sleeps, the function has a tendency to get stuck in an infinite loop. If this happens you will need to manually terminate the execution.

There is also the possibility of a corrupt API return. Because the geocoding is wrapped in a `try()` the function will output all of the results prior to the error. From there, you may specify the `start` argument to pick up where you left off.


The actual process is simple. It requries the data already be parsed into address, city, state and zip.
```{r cxy_full}
cxy_prep(orig, address, id, city, state, zip) %>%
  cxy_geocode() %>%
  cxy_join(orig)
```

